blog/urls.py
# blog/urls.py

from django.urls import path

from .views import (
    BlogDetailView,
    BlogsFilteredByTag,
    BlogListView,
)

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('tag/<slug:tag_pk>/', BlogsFilteredByTag.as_view(), name='blogs_filtered_by_tag'),
    path('<slug:pk>/', BlogDetailView.as_view(), name='blog_detail'),
]

core/urls.py
"""core URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
# home/urls.py

from django.urls import path

from .views import (
    IndexView,
)


app_name = 'home'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

blog/models.py
# blog/models.py
import uuid

from django.db import models
from django.utils import timezone


class Tag(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(
        max_length=50
    )

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'blog_tag'


class Group(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(
        max_length=50
    )

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'blog_group'


class Blog(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField(max_length=200)
    icon = models.ImageField(
        upload_to='blog_icon/',
        blank=True,
        null=True,
        verbose_name='main_image',
    )
    content = models.TextField()
    description = models.TextField(
        'article description',
        blank=True
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group_of'
    )
    is_published = models.BooleanField(
        'public status',
        default=True
    )
    created_at = models.DateTimeField(
        default=timezone.now
    )

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'blog_blog'

home/models.py
from django.db import models

# Create your models here.

blog/views.py
# blog/views.py

from django.views.generic import (
    ListView,
    TemplateView
)

from .models import Blog, Tag


class BlogListView(ListView):
    template_name = 'blog/blog_list.html'
    context_object_name = 'blog_list'
    paginate_by = 20

    def get_queryset(self):
        return Blog.objects.filter(
            is_published=True
        ).order_by('-created_at').defer('content')

    def get_context_data(self):
        context = super().get_context_data()
        return context


class BlogDetailView(TemplateView):
    template_name = 'blog/blog_detail.html'

    def get_blog(self, pk):
        blog = Blog.objects.select_related(
                'group'
            ).prefetch_related(
                'tags'
            ).get(pk=pk)
        return blog

    def get_related_posts(self, uid, group):
        related_posts = Blog.objects.filter(
                group=group
            ).exclude(
                id=uid
            ).defer('content')
        return related_posts

    def get_context_data(self, pk):
        context = super().get_context_data()

        blog = self.get_blog(pk)

        if (group := blog.group) is not None:
            related_posts = self.get_related_posts(blog.id, group)
            if len(related_posts) > 1:
                context.update({
                    'related_posts': related_posts
                })

        context.update({
            'blog': blog
        })
        return context


class BlogsFilteredByTag(ListView):
    template_name = 'blog/blogs_filtered_by_tag.html'
    context_object_name = 'blog_list'
    paginate_by = 20

    def get_queryset(self):
        return Blog.objects.filter(
            tags__pk=self.kwargs['tag_pk'],
            is_published=True
        ).order_by('created_at').defer('content')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update({
            'tag': Tag.objects.get(pk=self.kwargs['tag_pk'])
        })
        return context

home/views.py
# home/views.py

from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self):
        context = super().get_context_data()
        return context

templates/blog/blog_detail.html
{% extends "general/base.html" %}
{% load static %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog_detail.css' %}">
{% endblock %}
{% block content %}
<div id="blog_content_page">
    <div id="inner_blog_content_page">
        <h1 id="blog_title">{{ blog.title }}</h1>
        <div id="tag_block">
            <p id="tag_heading">Tag : </p>
            {% for tag in blog.tags.all %}
                <a
                    class="blog-tags"
                    href="{% url 'blog:blogs_filtered_by_tag' tag_pk=tag.pk %}"
                >{{ tag.name }}</a>
                {% if not forloop.last %}
                    <p class="tag-comma">,</p>
                {% endif %}
            {% endfor %}
        </div>
        <img src="{{ blog.icon.url }}" id="blog_icon" />
        <div id="content_block">
            {{ blog.content | safe }}
        </div>
    </div>
</div>
{% endblock %}

templates/blog/blog_list.html
{% extends "home/base.html" %}
{% load static %}
{% block link %}
<style type="text/css">
    #blog_list_page {
        padding: 15px 20px;
    }
    .blog-block {
        padding: 15px 10px;
    }
    .blog-title {
        font-size: 1.75rem;
        color: #333;
        text-decoration: none;
    }
    .blog-title:hover {
        text-decoration: underline solid #333;
    }
    #tag_heading {
        display: inline-block;
        margin-top: 5px;
        font-size: 0.9rem;
        color: #777;
    }
    .blog-tags {
        display: inline-block;
        font-size: 0.9rem;
        color: #009bc3;
    }
    .blog-tags:hover {
        text-decoration: underline solid #009bc3;
    }
    .blog-desc {
        margin-top: 5px;
        font-size: 0.9rem;
        color: #777;
        line-height: 27px;
    }
    .blog-icon {
        width: 90%;
    }
</style>
{% endblock %}
{% block content %}
<div id="blog_list_page">
    {% for blog in blog_list %}
    <div class="blog-block">
        <a href="{% url 'blog:blog_detail' pk=blog.pk %}" class="blog-title">{{ blog.title }}</a>
        <div id="tag_wrapper">
            <p id="tag_heading">Tag：</p>
            {% for tag in blog.tags.all %}
            <p class="blog-tags">{{ tag.name }}</p>
            {% endfor %}
        </div>
        <p class="blog-desc">{{ blog.description }}</p>
        <!-- <img src="{{ blog.icon.url }}" class="blog-icon"> -->
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/blog/blogs_filtered_by_tag.html
{% extends "general/base.html" %}
{% load static %}
{% block link %}
<style>
    #blogs_filtered_by_tag {
        padding: 0 20px 15px;
    }
    #tag_to_filter {
        text-align: center;
    }
    #tag_name_display {
        display: inline-block;
        padding: 4px 16px;
        font-size: 1.55rem;
        color: #333;
        background-color: #ececec;
        border-radius: 15px;
    }
    .blog-block {
        padding: 15px 10px;
    }
    .blog-title {
        font-size: 2.7rem;
        color: #333;
        text-decoration: none;
    }
    .blog-title:hover {
        text-decoration: underline solid #333;
    }
    #tag_heading {
        display: inline-block;
        margin-top: 8px;
        font-size: 1.55rem;
        color: #777;
    }
    .blog-tags {
        display: inline-block;
        font-size: 1.55rem;
        color: #009bc3;
        text-decoration: none;
    }
    .blog-tags:hover {
        text-decoration: underline solid #009bc3;
    }
    .list-tag-comma {
        display: inline-block;
        margin-right: 6px;
        font-size: 1.55rem;
    }
    .blog-desc {
        margin-top: 8px;
        font-size: 1.55rem;
        color: #777;
        line-height: 27px;
    }
    .blog-icon {
        width: 90%;
    }
</style>
{% endblock %}
{% block content %}　
<div id="blogs_filtered_by_tag">
    <div id="tag_to_filter">
        <p id="tag_name_display">Tag to filter : {{ tag.name }}</p>
    </div>
    {% for blog in blog_list %}
    <div class="blog-block">
        <a href="{% url 'blog:blog_detail' pk=blog.pk %}" class="blog-title">{{ blog.title }}</a>
        <div id="tag_wrapper">
            <p id="tag_heading">Tag：</p>
            {% for tag in blog.tags.all %}
                <a
                    href="{% url 'blog:blogs_filtered_by_tag' tag.pk %}"
                    class="blog-tags"
                >{{ tag.name }}</a>
                {% if not forloop.last %}
                <p class="list-tag-comma">,</p>
                {% endif %}
            {% endfor %}
        </div>
        <p class="blog-desc">{{ blog.description }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/general/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
        * {
            font-size: 10px;
            margin: 0;padding: 0;
            border: 0;
            background-repeat: repeat-y;
            font-family: "Open Sans", "Noto Sans", "PT Sans", Helvetica, Arial, sans-serif;
        }
        .link {
            position: absolute;top: 0;left:0;
            height: 100%;width: 100%;
            list-style: none;z-index: 9;
        }
        .clear { clear: both; }
        .block { display: block; }
        .none { display: none; }
        #home_header {
            padding: 20px 30px 15px;
            /* background: linear-gradient(to bottom, #01B2D3, #0077AF) */
            border-bottom: 1px solid #ccc;
        }
        #header_logo {
            display: inline-block;
            font-size: 3.3rem;
            color: #333;
        }
        #header_tag_grid {
            /*display: grid;
            max-width: 400px;
            grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));*/
            float: right;
            margin: 10px 0 0;
        }
        .home-header-tags {
            display: inline-block;
            padding: 0 0 8px;
            margin: 0 15px;
            text-decoration: none;
            font-size: 1.85rem;
            color: #333;
        }
        .home-header-tags:hover {
            border-bottom: 1px solid #aaa;
        }
        .active-tag {
            border-bottom: 1px solid #aaa;
        }
    </style>
    {% block link %}{% endblock %}
</head>
<body>
    <div id="page_wrapper">
        <div id="home_header">
            <p id="header_logo">BASIL</p>
            <div id="header_tag_grid">
                <a
                    href="/"
                    class="
                        home-header-tags
                        {% if request.path == '/' %}
                        active-tag
                        {% endif %}
                    "
                >
                    Home
                </a>
                <a
                    href="{% url 'blog:blog_list' %}"
                    class="
                        home-header-tags
                        {% if '/blog/' in request.path %}
                        active-tag
                        {% endif %}
                    "
                >
                    Blog
                </a>
                <a href="" class="home-header-tags">Projects</a>
            </div>
            <div class="clear"></div>
        </div>
        {% block content %}{% endblock %}
    </div>
    {% block script %}{% endblock %}
</body>
</html>

templates/home/index.html
{% extends "general/base.html" %}
{% load static %}
{% block link %}
<link rel="stylesheet" type="text/css" href="">
{% endblock %}
{% block content %}
{% endblock %}